# -*- coding: utf-8 -*-
"""TuVaAnh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zDLl8Il48emmA9-naOworzpk0nZe30br
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Mục mới"""

pip install opencv-contrib-python

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# sudo apt-get install libfftw3-dev libfftw3-doc

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/mlfw
# #unzip pyleargist-python3-master.zip
# cd pyleargist-python3-master
# python setup.py install

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/mlfw
# python runner.py

"""# Mục mới"""